spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: false
      uri: mongodb://localhost:27017/lowcoder?authSource=admin
    redis:
      url: redis://localhost:6379
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

logging:
  level:
    root: info
    web: debug

server:
  error:
    includeStacktrace: ALWAYS
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  http2:
    enabled: true
  port: 8080
  shutdown: graceful

default:
  orgs-per-user: 100
  org-member-count: 1000
  org-group-count: 100
  org-app-count: 1000
  developer-count: 50
  api-rate-limit: 50 

common:
  cookie-name: LOCAL_LOWCODER_TOKEN
  product: lowcoder
  domain:
    default-value: skipCheck
  encrypt:
    password: lowcoder
    salt: lowcoder
  cloud: true
  security:
    cors-allowed-domains:
      - '*'
  version: 2.1.4
  apiVersion: 1.1
  block-hound-enable: false
  js-executor:
    host: http://127.0.0.1:6060
  plugin-dirs:
    - /tmp/plugins
  super-admin:
    username: test@lowcoder.pro
    password: Password@123
  marketplace:
    private-mode: false

material:
  mongodb-grid-fs:
    bucket-name: material

springdoc:
  api-docs:
    path: /api/docs/api-docs
  swagger-ui:
    path: /api/docs/swagger-ui
  paths-to-exclude: /api/v1/**

auth:
  api-key:
    secret: 5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b
  email:
    enable: true
    enable-register: true
  workspace-creation: true